CREATE TABLE raw_vehicle_data (
    v_id NUMBER,
    constructor_name VARCHAR2(100),
    vehicle_type VARCHAR2(50),
    version VARCHAR2(50),
    brand VARCHAR2(100),
    vehicle_model VARCHAR2(100),
    vehicle_category VARCHAR2(10),
    kg_veh NUMBER,
    test_mass NUMBER,
    co2_wltp NUMBER,
    wheelbase_mm NUMBER,
    axle_width_steer_mm NUMBER,
    axle_width_other_mm NUMBER,
    energy VARCHAR2(50),
    engine_cm3 NUMBER,
    power_kw NUMBER,
    el_consumpt_whkm NUMBER,
    year NUMBER(4),
    fuel_consumption NUMBER,
    electric_range_km NUMBER,
    eco_innovation_program NUMBER,
    em_on_target NUMBER
);